FROM ubuntu:22.04
WORKDIR /app

COPY ./client_hw_1_1.c ./
RUN apt update -y && apt install gcc -y
RUN gcc client_hw_1_1.c -o main
RUN bash -c 'echo -e "TEST_MSG\n" > serv.conf'
EXPOSE 8888/tcp

CMD ["bash", "-c", "./main --server server < serv.conf"]
